version: '3.8'

services:
  frontend-funclub:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend-funclub
    restart: unless-stopped
    networks:
      - edge
    expose:
      - 80
    labels:
      - traefik.enable=true
      - traefik.http.routers.frontend-funclub.entryPoints=https
      - traefik.http.routers.frontend-funclub.rule=Host(`${DOMAIN}`)
    environment:
      - TZ=${TZ}

networks:
  edge:
    external: true
